#!/bin/bash

function php_context {
  case $OPENSHIFT_PHP_VERSION in
    7.0) /usr/bin/scl enable php70 "$1" ;;
  esac
}

function update_configuration {
  # PEAR bin_dir
  local path=${OPENSHIFT_PHP_DIR}phplib/pear/pear:${OPENSHIFT_HOMEDIR}.composer/vendor/bin

  case $OPENSHIFT_PHP_VERSION in
    7.0)
      # SCL bin_dir
      path=$(path_append ${path:-:} $(dirname $(scl enable php70 "which php") | tr -d '\n'))

      local man_path=$(MANPATH="" scl enable php70 "printenv MANPATH")
      path_append ${MANPATH:-:} ${man_path:-:} > ${OPENSHIFT_PHP_DIR}env/MANPATH
      ;;
  esac

  # Composer
  path=$(path_append ${path:-:} ${OPENSHIFT_PHP_DIR}usr/bin)

  echo $path > ${OPENSHIFT_PHP_DIR}env/OPENSHIFT_PHP_PATH_ELEMENT
}
